### ISSUE TITLE
Getting an error... can't RSVP

### ISSUE THREAD

**Issue by lorelei1** [wearekickback/app#47]
Tried to sign up for an event and had to create a username and all that with metamask... then the login works but i can't rsvp for this event or another event. 

<img width="1158" alt="screen shot 2018-10-28 at 11 27 54 pm" src="https://user-images.githubusercontent.com/38163206/47622792-8bb6c600-db09-11e8-8e69-5ac20bdaeb04.png">

I'm on a 2015 macbook pro, pretty much up to date, using chrome.

Thanks for making such a beautiful and fun app :-D

**Comment by hiddentao** [comment]
Hey, thanks for the feedback. A few other users have had this and we figured out eventually it's due to Metamask issues. It might be worth resetting the account within Metamask (_settings_ -> _reset account_). I know one other user uninstalled and then reinstalled Metamask to get things working. You could also try it in a different desktop browser.
